name: Java SDK Release

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build-and-publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  token: ${{ secrets.GH_TOKEN }}
                  fetch-depth: 0

            - name: Set up JDK
              uses: actions/setup-java@v3
              with:
                  distribution: 'adopt'
                  java-version: '11'

            - name: Build with Maven
              run: mvn clean package

            - name: Run tests
              run: mvn test

            - name: Extract Version from pom.xml
              id: extract_version
              run: |
                  version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
                  echo "Project version: $version"
                  echo "::set-output name=version::$version"

            - name: Set Git user
              run: |
                  git config user.name "github-actions"
                  git config user.email "github-actions@github.com"

            - name: Authenticate with GitHub
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
              run: |
                  git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/Vyper-Terminal/vyper-client-java.git

            - name: Create and push tag
              run: |
                  git tag ${{ steps.extract_version.outputs.version }}
                  git push origin ${{ steps.extract_version.outputs.version }}

            - name: Verify JitPack Build
              run: |
                  curl -s https://jitpack.io/com/github/Vyper-Terminal/vyper-client-java/${{ steps.extract_version.outputs.version }}/build.log
